[theme]

# Primary accent for interactive elements
primaryColor = '#ff7f50'

# Background color for the main content area
backgroundColor = '#fff0f5'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ff7f50'

# Color used for almost all text
textColor = '#696969'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"